# Generated by Django 4.2.17 on 2025-01-17 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0003_delete_backendvacancy_alter_vacancy_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=255, unique=True)),
                ('html_content', models.TextField()),
            ],
        ),
    ]
